acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern:  /
    defaults: { _controller: AcmeRentacarBundle:Reservation:index }

AcmeRentacarBundle:
    resource: "@AcmeRentacarBundle/Controller/"
    type:     annotation
    prefix:   /
