acme_rentacar:
    resource: "@AcmeRentacarBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /


